export CVS_RSH=ssh
export EDITOR=vim
export LC_COLLATE=C
export LC_CTYPE="sv_SE.UTF-8"
export LC_MESSAGES="en_GB.UTF-8"
export LC_MONETARY="sv_SE.UTF-8"
export LC_NUMERIC="sv_SE.UTF-8"
export LC_PAPER="sv_SE.UTF-8"
export LC_TIME="sv_SE.UTF-8"
export TZ=CET
export HISTSIZE=13000
export SAVEHIST=12000
export HISTFILE=~/.history
export VIMHOME=${HOME}/.vim
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='3;33'
export BLOCKTABLE="attackers"
export WORKON_HOME=~/.envs
export TODOTXT_DEFAULT_ACTION='ls'
export NOTES_DIR=/Users/sjk/Documents/Skola/SHH/notes
#export PIP_REQUIRE_VIRTUALENV=true
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export ANSIBLE_NOCOWS=1
export PYENV_ROOT='$HOME/.pyenv'
export MPD_HOST='tweed.glams.sjk.io'
export MPD_PORT=6600
export JOHNNYDECIMAL_BASE=~/Documents/

typeset -U path
path=(
    ~/bin
    $PYENV_ROOT/bin
    /opt/homebrew/bin
    /Library/TeX/Distributions/Programs/texbin
    /usr/local/sbin
    $path
)

