source ~/.zsh/settings.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
source ~/config/zsh-plugins/syntax-highlighting/zsh-syntax-highlighting.zsh

if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    source /usr/local/bin/virtualenvwrapper.sh
fi

if [ -f ~/.zsh_extra ]; then
    source ~/.zsh_extra
fi


# added by travis gem
[ -f /Users/sjk/.travis/travis.sh ] && source /Users/sjk/.travis/travis.sh
