source ~/.zsh/settings.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/johnnydecimal.zsh

if [[ $(uname 2> /dev/null) == "Darwin" ]]; then
    source ~/.zsh/osx.zsh
fi

source ~/config/zsh-plugins/syntax-highlighting/zsh-syntax-highlighting.zsh

# if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
#     source /usr/local/bin/virtualenvwrapper.sh
# fi

# For some reason the Debian virtualenvwrapper places the script in
# /etc/bash_completion.d.
# if [ -f /etc/bash_completion.d/virtualenvwrapper ]; then
#     source /etc/bash_completion.d/virtualenvwrapper
# fi

# if command -v pyenv 1>/dev/null 2>&1;
# then
#     eval "$(pyenv init -)"
# fi

if [ -f ~/.zsh_extra ]; then
    source ~/.zsh_extra
fi


# added by travis gem
[ -f /Users/sjk/.travis/travis.sh ] && source /Users/sjk/.travis/travis.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
